name: Write_and_check

on: 
  pull_request:
    branches:
      -main

jobs:
  tests:
    run_on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/checkout@v4
      with:
        python-version: "3.11"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Якщо в тебе є requirements.txt, ставимо з нього:
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Додатково гарантуємо наявність пакетів для тестів та FastAPI
        pip install pytest fastapi httpx pydantic langchain-core langchain-openai langgraph

    - name: Run pytest
      run: |
        # Вказуємо шлях до нашого файлу тестів API
        pytest test_main_api.py -v
